# Generated by Django 5.1.7 on 2025-04-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicare', '0002_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(max_length=300, upload_to='uploads/'),
        ),
    ]
